### ISSUE TITLE
Missing a link to this repository in the tutorial

### ISSUE THREAD

**Issue by unknownterritory** [vercel/beginner-sveltekit#21]
My kid is following your tutorial and we noticed that there doesn't seem to be a link to this repository anywhere in it. As we found out about the tutorial first, we only went searching for this repository after things started getting a bit weird... trying to follow and update the code based just on the contents of each lesson. I would suggest including a link to this repository maybe at the [Getting Started](https://vercel.com/docs/beginner-sveltekit/getting-started) page of the tutorial so others may not have to go through the same experience.

Otherwise, great tutorial, thank you!

**Comment by StephDietz** [comment]
Hello! Each module links to this repository at the top of the page (beneath the video) 
<img width="685" alt="Screen Shot 2022-11-30 at 8 58 03 AM" src="https://user-images.githubusercontent.com/49788645/204832187-e6a4870e-81b2-4ed5-8a20-4a7a5897c31f.png">
However this is good feedback. I will look into making it more obvious that this is a link to the code :) Glad you are enjoing the course so far!
