### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by cassiofb-dev** [vercel/beginner-sveltekit#22]
Hi, I'm learning Svelte on this awesome course.

I found some typos on [https://vercel.com/docs/beginner-sveltekit/element-directives](https://vercel.com/docs/beginner-sveltekit/element-directives) and I don't know where to change.

**Comment by leerob** [comment]
Hey! If you let us know here, we can get them updated. Thank you.

**Comment by cassiofb-dev** [comment]
Wow, that was quick. I'm trying some example codes on Svelte sandbox page and some ``}`` are missing on some closing ``if`` statements.

![image](https://user-images.githubusercontent.com/61878987/211442388-a003ca93-c83a-4891-b479-da4be9667b2f.png)

**Comment by cassiofb-dev** [comment]
Update: The page is [https://vercel.com/docs/beginner-sveltekit/conditionals-and-loops](https://vercel.com/docs/beginner-sveltekit/conditionals-and-loops) got the wrong one 😔

**Comment by leerob** [comment]
Thank you! We fixed this.
