### ISSUE TITLE
Questions about modules after SvelteKit's load and routing changes

### ISSUE THREAD

**Issue by jzavala-gonzalez** [vercel/beginner-sveltekit#3]
Hi everyone, thank you for making this course! I've been waiting to dive into SvelteKit and this looks like a fantastic starting point. I am wondering what are the plans for some of the modules of the course given the updates to the routing and load API described in https://github.com/sveltejs/kit/discussions/5748 . Are there any plans to update the corresponding course modules? Or would waiting until 1.0 before any further changes be more likely? I'll work through pieces of the course in the meantime; just want to know how to approach the routing and load related portions. Thank you for any feedback, and have a nice day!

**Comment by StephDietz** [comment]
As changes are made we will update the written portion of the course!

**Comment by michaelphipps** [comment]
If you want to do this course as it exists prior to the load and routing changes (which it still did at the time of this comment), you can install an older version of SvelteKit just to do the course, however It doesn't really make sense to learn information that is out of date method.

To install the version prior to the routing change:
```
npm init svelte@next
```
Update `pacakge.json` to:
```
"devDependencies": {
    "@sveltejs/kit": "1.0.0-next.405",
    ...
```
THEN run `npm install`

**Comment by leerob** [comment]
Closing this out since the course has been updated 😄
